Rewrite build status messages
openafs-contrib/afsbotcfg pull request #24
Opened 2023-05-26 18:42 UTC by CheyenneWills

The messages associated with reporting the build status are confusing.

Update the "Final Build Status" line to remove the parentheses and better associate the labels with their counts.

Update the worker timeout message to indicate that a "critical" worker timed out.

2023-05-30 15:00 UTC, meffie requested changes

2023-05-30 15:00 UTC, meffie commented on src/afsbotcfg/gerrit.py
> +    msgs.append("Final Build Status: failed: %d, succeeded: %d, skipped: %d" %
But this is still confusing, because it is not the final status imho. It doesn't say if the buildbot votes +1 or not. Also, the order seems strange. I think most systems report in the order Pass, Fail, Skipped. Can we change it to something like ?

Buildbot Verification [Passed| Failed]
  Passed: x
  Failed: x
  Skipped: x

2023-05-30 16:36 UTC, CheyenneWills commented on src/afsbotcfg/gerrit.py
> +    msgs.append("Final Build Status: failed: %d, succeeded: %d, skipped: %d" %
The vote +1 or not is shown above these messages:

```
Patch Set 4: Verified+1

The OpenAFS Buildbot Coordinator

https://buildbot.openafs.org/

Final Build Status (failed 0 succeeded 25 skipped 0):
```

The "Patch Set x: Verified+1" is produced by Gerrit directly (I believe).

But yes -- I can reword the message.  I was trying to keep it as a one liner, but if you want it split into separate lines I can do that as well..

2023-05-31 19:11 UTC, CheyenneWills commented
I've added a Passed/Failed status and swapped the Succeeded/Failed counts.  I've left them as a single line since it shows up well on the gerrit webbase

2023-06-02 12:32 UTC, meffie approved these changes

2023-06-02 12:32 UTC, merged

2023-06-02 12:34 UTC, meffie commented
Seems you didn't run lint before pushing :(

$ make lint
==> Running lint checks <==
make -C src lint
make[1]: Entering directory '/home/mmeffie/src/afsbotcfg/src'
pyflakes afsbotcfg/*.py
afsbotcfg/gerrit.py:78:38: invalid syntax
                "Passed" if verified = 1 else "Failed",
                                     ^
make[1]: *** [Makefile:27: lint] Error 1
make[1]: Leaving directory '/home/mmeffie/src/afsbotcfg/src'
make: *** [Makefile:127: lint] Error 2

2023-06-02 12:38 UTC, meffie commented
I pushed a fix. Can you add a 'make lint' to your git commit hook?

2023-06-02 14:49 UTC, meffie commented
Fails with an exception. I'll revert it for now.

40791 2023-06-02 10:20:54-0400 [-] Unhandled error in Deferred:
40792 2023-06-02 10:20:54-0400 [-] Unhandled Error
40793     Traceback (most recent call last):
40794       File "/home/buildbot/.venv/buildbot/lib64/python3.6/site-packages/twisted/internet/defer.py", line 141      8, in _inlineCallbacks
40795         result = g.send(result)
40796       File "/home/buildbot/.venv/buildbot/lib64/python3.6/site-packages/buildbot/reporters/gerrit.py", line       341, in buildsetComplete
40797         self.sendBuildSetSummary(buildset, builds)
40798       File "/home/buildbot/.venv/buildbot/lib64/python3.6/site-packages/twisted/internet/defer.py", line 161      3, in unwindGenerator
40799         return _cancellableInlineCallbacks(gen)
40800       File "/home/buildbot/.venv/buildbot/lib64/python3.6/site-packages/twisted/internet/defer.py", line 152      9, in _cancellableInlineCallbacks
40801         _inlineCallbacks(None, g, status)
40802     --- <exception caught here> ---
40803       File "/home/buildbot/.venv/buildbot/lib64/python3.6/site-packages/twisted/internet/defer.py", line 141      8, in _inlineCallbacks
40804         result = g.send(result)
40805       File "/home/buildbot/.venv/buildbot/lib64/python3.6/site-packages/buildbot/reporters/gerrit.py", line       370, in sendBuildSetSummary
40806         self.summaryArg)
40807       File "/home/buildbot/.venv/buildbot/lib64/python3.6/site-packages/afsbotcfg/gerrit.py", line 78, in su      mmaryCB
40808         "Passed" if verified == 1 else "Failed",
40809     builtins.TypeError: not enough arguments for format string